services:
  lint:
    build:
      context: .
      target: dev
    command: ruff check /app
    volumes:
      - ./app:/app

  format:
    build:
      context: .
      target: dev
    command: ruff format --check /app
    volumes:
      - ./app:/app

  pytest:
    build:
      context: .
      target: dev
    command: pytest /tests
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app:/app
      - ./tests:/tests

  run:
    image: wonkyto/ubnt-switch-collector:1.1.0
    volumes:
      - ./config:/config
      - ./key:/key
    working_dir: /app

  test:
    image: wonkyto/ubnt-switch-collector:1.1.0
    volumes:
      - ./app:/app
      - ./config:/config
      - ./key:/key
    working_dir: /app
